name: rdna-miner

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.11
  - pip
  - typer
  - pandas
  - biopython
  - numpy
  - matplotlib
  - gdown

  # bioinf
  - barrnap
  - flye
  - minimap2
  - samtools
  - infernal

  # R
  - r-base
  - bioconductor-decipher
  - r-dplyr
  - r-tidyr
  #- r-data.table

  #utils
  - seqkit
  - pigz

  # pip installs
  - pip:
      - rich